---
name: "Nautobot Upstream Monitor"

on:  # yamllint disable-line rule:truthy rule:comments
  workflow_dispatch:

jobs:
  upstream-test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - nautobot_branch: "develop"
            app_branch: "main"
          - nautobot_branch: "next"
            app_branch: "main"
          - nautobot_branch: "ltm-2.4"
            app_branch: "ltm-2.4"
    uses: "nautobot/nautobot/.github/workflows/plugin_upstream_testing_base.yml@develop"
    with:
      invoke_context_name: "NAUTOBOT_FUNCTION_CODES"
      app_name: "nautobot-function-codes"
      nautobot_branch: "${{ matrix.nautobot_branch }}"
      app_branch: "${{ matrix.app_branch }}"
